name: Docker test

on:
  push:
  pull_request:

env:
  IMAGE_NAME: force

jobs:
  push:
    name: Test whether Docker image builds successfully
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
