name: unit-testing

on:
  push:
    branches: ['*']
  release:
    types: [published]
  repository_dispatch:
    types: [udf-dispatch]

jobs:
  testing:
    name: Compile and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Compile all units
        run: make unit-tests
      - name: Test all units
        run: make unit-testing
      - name: Clean
        run: make clean
