name: unit-testing

on:
  push:
    branches: ['*']
  release:
    types: [published]
  repository_dispatch:
    types: [udf-dispatch]

jobs:
  testing:
    name: Compile and run unit tests
    runs-on: ubuntu-latest
    container:
      image: davidfrantz/base
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Compile all units
        run: make unit-tests
      - name: Test all units
        run: make unit-testing
      - name: Clean up
        run: make clean
